// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: internal/proto/usersrv.proto

package rpcmoviex

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the fetch users request parameters
type FetchUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumRecords  int32 `protobuf:"varint,1,opt,name=numRecords,proto3" json:"numRecords,omitempty"`
	FirstRecord int32 `protobuf:"varint,2,opt,name=firstRecord,proto3" json:"firstRecord,omitempty"`
}

func (x *FetchUsersRequest) Reset() {
	*x = FetchUsersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_usersrv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchUsersRequest) ProtoMessage() {}

func (x *FetchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_usersrv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchUsersRequest.ProtoReflect.Descriptor instead.
func (*FetchUsersRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_usersrv_proto_rawDescGZIP(), []int{0}
}

func (x *FetchUsersRequest) GetNumRecords() int32 {
	if x != nil {
		return x.NumRecords
	}
	return 0
}

func (x *FetchUsersRequest) GetFirstRecord() int32 {
	if x != nil {
		return x.FirstRecord
	}
	return 0
}

// The response message containing user list
type FetchUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users        []*FetchUserResponse `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalRecords int32                `protobuf:"varint,2,opt,name=totalRecords,proto3" json:"totalRecords,omitempty"`
}

func (x *FetchUsersResponse) Reset() {
	*x = FetchUsersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_usersrv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchUsersResponse) ProtoMessage() {}

func (x *FetchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_usersrv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchUsersResponse.ProtoReflect.Descriptor instead.
func (*FetchUsersResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_usersrv_proto_rawDescGZIP(), []int{1}
}

func (x *FetchUsersResponse) GetUsers() []*FetchUserResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *FetchUsersResponse) GetTotalRecords() int32 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

// The response message containing user
type FetchUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *FetchUserResponse) Reset() {
	*x = FetchUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_usersrv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchUserResponse) ProtoMessage() {}

func (x *FetchUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_usersrv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchUserResponse.ProtoReflect.Descriptor instead.
func (*FetchUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_usersrv_proto_rawDescGZIP(), []int{2}
}

func (x *FetchUserResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FetchUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FetchUserResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_internal_proto_usersrv_proto protoreflect.FileDescriptor

var file_internal_proto_usersrv_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x11, 0x46, 0x65, 0x74, 0x63, 0x68, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x75,
	0x6d, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x6e, 0x75, 0x6d, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x66, 0x69, 0x72, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x68, 0x0a, 0x12,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x55, 0x0a, 0x11, 0x46, 0x65, 0x74, 0x63, 0x68, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x32, 0x49, 0x0a,
	0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x0a, 0x66, 0x65, 0x74, 0x63, 0x68, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x74, 0x6f, 0x6c,
	0x79, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x78, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x3b, 0x72, 0x70, 0x63, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_proto_usersrv_proto_rawDescOnce sync.Once
	file_internal_proto_usersrv_proto_rawDescData = file_internal_proto_usersrv_proto_rawDesc
)

func file_internal_proto_usersrv_proto_rawDescGZIP() []byte {
	file_internal_proto_usersrv_proto_rawDescOnce.Do(func() {
		file_internal_proto_usersrv_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_usersrv_proto_rawDescData)
	})
	return file_internal_proto_usersrv_proto_rawDescData
}

var file_internal_proto_usersrv_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_usersrv_proto_goTypes = []interface{}{
	(*FetchUsersRequest)(nil),  // 0: proto.FetchUsersRequest
	(*FetchUsersResponse)(nil), // 1: proto.FetchUsersResponse
	(*FetchUserResponse)(nil),  // 2: proto.FetchUserResponse
}
var file_internal_proto_usersrv_proto_depIdxs = []int32{
	2, // 0: proto.FetchUsersResponse.users:type_name -> proto.FetchUserResponse
	0, // 1: proto.User.fetchUsers:input_type -> proto.FetchUsersRequest
	1, // 2: proto.User.fetchUsers:output_type -> proto.FetchUsersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_usersrv_proto_init() }
func file_internal_proto_usersrv_proto_init() {
	if File_internal_proto_usersrv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_usersrv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_usersrv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchUsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_usersrv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_usersrv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_usersrv_proto_goTypes,
		DependencyIndexes: file_internal_proto_usersrv_proto_depIdxs,
		MessageInfos:      file_internal_proto_usersrv_proto_msgTypes,
	}.Build()
	File_internal_proto_usersrv_proto = out.File
	file_internal_proto_usersrv_proto_rawDesc = nil
	file_internal_proto_usersrv_proto_goTypes = nil
	file_internal_proto_usersrv_proto_depIdxs = nil
}
