// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Actor struct {
	ID         string `json:"id"`
	FirstName  string `json:"firstName"`
	LastName   string `json:"lastName"`
	LastUpdate int64  `json:"lastUpdate"`
}

type Category struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	LastUpdate int64  `json:"lastUpdate"`
}

type Film struct {
	ID       string    `json:"id"`
	Title    string    `json:"title"`
	Category *Category `json:"category"`
	Actors   []*Actor  `json:"actors"`
}

type FilmEdge struct {
	Node *Film `json:"node"`
}

type FilmPage struct {
	TotalCount int32       `json:"totalCount"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	Edges      []*FilmEdge `json:"edges"`
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor"`
}

type User struct {
	ID       int32  `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserEdge struct {
	Node *User `json:"node"`
}

type UserPage struct {
	TotalCount int32       `json:"totalCount"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	Edges      []*UserEdge `json:"edges"`
}
